model: BasicSeq2Seq
model_params:
  bridge.class: seq2seq.models.bridges.InitialStateBridge
  embedding.dim: 256
  encoder.class: seq2seq.encoders.TwoToOneEncoder
  encoder.params:
    rnn_cell0:
      cell_class: LSTMBlockCell
      cell_params:
        num_units: 256
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 1
    rnn_cell1:
      cell_class: LSTMBlockCell
      cell_params:
        num_units: 256
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 1
  decoder.class: seq2seq.decoders.BasicDecoder
  decoder.params:
    rnn_cell:
      cell_class: LSTMBlockCell
      cell_params:
        num_units: 256
      dropout_input_keep_prob: 0.8
      dropout_output_keep_prob: 1.0
      num_layers: 2
  optimizer.name: Adam
  optimizer.learning_rate: 0.0001
  source.max_seq_len: 1482
  source.reverse: true
  target.max_seq_len: 1482