#!/bin/bash

python3 train.py --task "A" --num_epochs 5 --model_name "A_Vanilla" --learning_rate 0.01
python3 train.py --task "B" --num_epochs 5 --model_name "B_Vanilla" --learning_rate 0.01
python3 train.py --task "C" --num_epochs 5 --lstm_size 1024 --model_name "C_Vanilla" --learning_rate 0.01

# Shut down computer after the work is done
shutdown -P +5
