#!/bin/bash


python3 train.py --task="C" --is_training=True --is_eval=False --is_cont=False --force_init=True --lstm_size=1024 --learning_rate=0.01
#python3 train.py --task "C" --num_epochs 1 --lstm_size 1024 --allow_batchnorm True --dropout_rate 0.5 --model_name "C__BN_drop"


